Feature/as 556602591218327 add styling for header
thedataplace/bakerydemo pull request #1
Opened 2018-02-18 17:01 UTC by joshJarr

https://app.asana.com/0/2524932960023

2018-02-18 17:06 UTC, joshJarr commented on bakerydemo/templates/includes/header.html
> +                </form> -->
unsure if this search is required. Commented out for now.

2018-02-18 17:07 UTC, joshJarr commented on readme.md
> +docker-compose run app /venv/bin/python manage.py createsuperuser #Follow the instructions, name your user `admin`
Lemme know if this seems vague, or is even necessary.
Needed to run this before I could load the test data.

2018-02-19 09:22 UTC, gerbyzation requested changes

2018-02-19 09:22 UTC, gerbyzation commented on readme.md
>  git clone git@github.com:wagtail/bakerydemo.git
This is the wrong URL, and HTTPS might be preferable as a default?

2018-02-19 11:08 UTC, thisisthechris approved these changes
Looks great, can't spot any issues.

2018-02-19 11:08 UTC, merged